### ISSUE TITLE
port in URL is not converted to integer

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy-collectd#3]
pretty basic stuff!

```
>>> e = create_engine("mysql+pymysql://nova_api:7aTeVvzTKDNB58gqi6Z51yB27@10.0.20.36/nova_api?read_default_file=/etc/my.cnf.d/tripleo.cnf&read_default_group=tripleo&plugin=collectd&collectd_host=localhost&collectd_port=25827")
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy_collectd/client/worker.py", line 37, in _process
    sender.send(connection, collection_target, now, interval, pid)
  File "/usr/lib/python3.6/site-packages/sqlalchemy_collectd/client/sender.py", line 29, in send
    sender(message_sender, connection, collection_target, timestamp)
  File "/usr/lib/python3.6/site-packages/sqlalchemy_collectd/client/sender.py", line 41, in _send_pool
    collection_target.num_connections
  File "/usr/lib/python3.6/site-packages/sqlalchemy_collectd/protocol.py", line 154, in send
    connection.send(header_ + payload)
  File "/usr/lib/python3.6/site-packages/sqlalchemy_collectd/protocol.py", line 315, in send
    self.socket.sendto(message, (self.host, self.port))
TypeError: an integer is required (got type str)

```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Coerce port to integer** https://gerrit.sqlalchemy.org/1396
