### ISSUE TITLE
KeyError: 4

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy-collectd#4]
starting up in collectd server, got this:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy_collectd/server/listener.py", line 6, in _receive
    receiver.receive(connection)
  File "/usr/lib/python3.6/site-packages/sqlalchemy_collectd/server/receiver.py", line 37, in receive
    message = self.message_receiver.receive(data)
  File "/usr/lib/python3.6/site-packages/sqlalchemy_collectd/protocol.py", line 225, in receive
    type_name = result[TYPE_TYPE]
KeyError: 4

```

**Comment by zzzeek** [comment]
OK so this is just because I was trying to wake it up and did this:

```
# nc -u 127.0.0.1 25827
askdjadkj

asdadsfd

```

then because of #5 the whole thread crashed and it didn't log it.  so #5 is more critical here.

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Catch KeyError for TYPE_TYPE missing in message** https://gerrit.sqlalchemy.org/1397
